export const REDUX = {
  CLEAR_DATA: 'CLEAR_DATA',
  //AUTH REDUCER:
  LOGIN: 'LOGIN',
  UPDATE_USER_DATA: 'UPDATE_USER_DATA',
  UPDATE_REFRESH_TOKEN: 'UPDATE_REFRESH_TOKEN',
  UPDATE_ACCESS_TOKEN: 'UPDATE_ACCESS_TOKEN',
  //SREACH REDUCER:
  UPDATE_SEARCH_RESULT: 'UPDATE_SEARCH_RESULT',
  GET_TOP_RATING: 'GET_TOP_RATING',
  GET_ALL_MAININGREDIENT:'GET_ALL_MAININGREDIENT',
  //FAVORITE REDUCER
  GET_FAVORITE_LIST: 'GET_FAVORITE_LIST',
  ADD_TO_FAVORITE: 'ADD_TO_FAVORITE',
  REMOVE_FROM_FAVORITE: 'REMOVE_FROM_FAVORITE',
};
